services:
  - type: web
    name: rpe-training-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
    plan: free
    healthCheckPath: /api/health
    autoDeploy: true
    disk:
      name: sqlite-data
      mountPath: /data
      sizeGB: 1
    scaling:
      minInstances: 0
      maxInstances: 1
      targetMemoryPercent: 80

  - type: web
    name: rpe-training-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://rpe-training-backend.onrender.com
    plan: free
    autoDeploy: true
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=31536000, immutable 